### ISSUE TITLE
cos(1)+logE(exp(1)) returns nan

### ISSUE THREAD

**Issue by livibetter** [lkpdn/tcalc#2]
It should return 1.540302, and `logE(exp(1))+cos(1)` does return that.

**Comment by lkpdn** [comment]
Thank you for your attention!
Actually ```cos``` part had to be ```cos_``` back then. Quite ugly, isn't it? :p 
So I made a fix commit here: https://github.com/lkpdn/tcalc/commit/6552b4cb9f19e9b3ce60dfbf96e5323673c9a745

**Comment by livibetter** [comment]
It seems to break even more, using 8dabac8fdca40c5b0455eda0d4131b7832a4fece, now even `logE(exp(1))+cos(1)` returns nan.

By the way, do you know why TCalc requires so much to compile, I observed 1297-228=1069 memory usage, I know some C++ projects really memory hogging in compilation, but TCalc shouldn't have reached that stage, should it?

**Comment by lkpdn** [comment]
Now ```logE``` never exists. You might see ```log``` label on buttons.
I guess it's due to an external library.

**Comment by livibetter** [comment]
Didn't pay attention to the diff and the buttons. Closing.
