### ISSUE TITLE
Up/Down and PageUp/Down to flip buttons page

### ISSUE THREAD

**Issue by livibetter** [lkpdn/tcalc#3]
I found the current navigation is a bit of inconvenient.

It would be much better if you can use:

* <kbd>Up</kbd> from any button of first row to go up one page
* <kbd>Down</kbd> from any button of last row to go down one page
* <kbd>PageUp</kbd> from any button to go up one page
* <kbd>PageDown</kbd> from any button to go down one page
* <kbd>Escape</kbd> to de-select/deactivate, maybe even `Clr`?

Also, when first press <kbd>Down</kbd> to activate the buttons, it's a bit odd that you land on the last button of first row.

**Comment by lkpdn** [comment]
> * <kbd>Up</kbd> from any button of first row to go up one page
> * <kbd>Down</kbd> from any button of last row to go down one page
> * <kbd>PageUp</kbd> from any button to go up one page
> * <kbd>PageDown</kbd> from any button to go down one page
> * <kbd>Escape</kbd> to de-select/deactivate, maybe even `Clr`?

The above all would make it more intuitive. Fix commit: https://github.com/lkpdn/tcalc/commit/8dabac8fdca40c5b0455eda0d4131b7832a4fece

> Also, when first press <kbd>Down</kbd> to activate the buttons, it's a bit odd that you land on the last button of first row.

I totally agree with you. The fix commit is here: https://github.com/lkpdn/tcalc/commit/49862e2344d52251b3c475fd8526abce8155caf3

Thanks for all. I wonder if you could make pull requests when you will find out any other points.

**Comment by livibetter** [comment]
Did you meant me to contribute C++ codes? If it's, unfortunately, I can't code C++. But if you meant to open a pull request for keeping anything I want instead of opening several issues. I don't think it can be done without code/branch involving.

Since this is done, closing.

**Comment by lkpdn** [comment]
I meant coding but its okay. Thanks!
